---
title: "Part2-Q1"
author: "Tianjiao Mei" "Yongfan Zhao"
date: "2023-10-01"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load library

```{r}
library(tidyverse)
library(data.table)
library(knitr)
library(kableExtra)
library(cowplot)
```


## CK1994: Data Preparation

```{r}
in_path <- dirname(getwd())

ck1994_raw_data <- read.table(file.path(in_path, 'Data', 'Raw', 'ck1994_data.dat'))

name_changes <- c('SHEET', 'CHAIN', 'CO_OWNED', 'STATE', 'SOUTHJ', 'CENTRALJ',
             'NORTHJ', 'PA1', 'PA2', 'SHORE', 'NCALLS', 'EMPFT', 'EMPPT',
             'NMGRS', 'WAGE_ST', 'INCTIME', 'FIRSTINC', 'BONUS', 'PCTAFF',
             'MEALS', 'OPEN', 'HRSOPEN', 'PSODA', 'PFRY', 'PENTREE', 'NREGS',
             'NREGS11', 'TYPE2', 'STATUS2', 'DATE2', 'NCALLS2', 'EMPFT2',
             'EMPPT2', 'NMGRS2', 'WAGE_ST2', 'INCTIME2', 'FIRSTIN2', 'SPECIAL2',
             'MEALS2', 'OPEN2R', 'HRSOPEN2', 'PSODA2', 'PFRY2', 'PENTREE2', 
             'NREGS2','NREGS112')

ck1994_raw_data_col <- ck1994_raw_data %>%
  set_names(name_changes)
```


```{r}
ck1994_new <- ck1994_raw_data_col %>%
  mutate(BK = case_when(CHAIN == 1 ~ 1,TRUE ~ 0),
         KFC = case_when(CHAIN == 2 ~ 1,TRUE ~ 0),
         RR = case_when(CHAIN == 3 ~ 1,TRUE ~ 0),
         WD = case_when(CHAIN == 4 ~ 1,TRUE ~ 0)) %>%
  
  mutate(wage_4.25 = case_when(WAGE_ST == 4.25 ~ 1, TRUE ~ 0),
         wage2_4.25 = case_when(WAGE_ST2 == 4.25 ~ 1, TRUE ~ 0),
         wage2_5.05 = case_when(WAGE_ST2 == 5.05 ~ 1, TRUE ~ 0)) %>%
  
  mutate(EMPFT = as.numeric(EMPFT),
         NMGRS = as.numeric(NMGRS),
         EMPPT = as.numeric(EMPPT),
         EMPFT2 = as.numeric(EMPFT2),
         NMGRS2 = as.numeric(NMGRS2),
         EMPPT2 = as.numeric(EMPPT2),
         WAGE_ST = as.numeric(WAGE_ST),
         WAGE_ST2 = as.numeric(WAGE_ST2),
         PSODA = as.numeric(PSODA),
         PSODA2 = as.numeric(PSODA2),
         PFRY = as.numeric(PFRY),
         PFRY2 = as.numeric(PFRY2),
         PENTREE = as.numeric(PENTREE),
         PENTREE2 = as.numeric(PENTREE2),
         HRSOPEN2 = as.numeric(HRSOPEN2),
         SPECIAL2 = as.numeric(SPECIAL2)) %>%
  
  mutate(FTE = EMPFT + NMGRS + (0.5)*EMPPT,
         FTE2 = EMPFT2 + NMGRS2 + (0.5)*EMPPT2) %>%
  mutate(Fulltime_Perc = (EMPFT/FTE)*100,
         Fulltime_Perc2 = (EMPFT2/FTE2)*100) %>%
  mutate(PFULL = PSODA + PFRY + PENTREE,
       PFULL2 = PSODA2 + PFRY2 + PENTREE2) %>%
  mutate(FTE_change = FTE2-FTE)
```

---------------------------------------------------------------------------------

# 1(a). Table 2

## Table 2 - 1

```{r}
# Calculate store distribution means:

store_dist <- ck1994_new %>% 
  group_by(STATE) %>%
  summarise(mean_BK = mean(BK, na.rm=T),
            mean_KFC = mean(KFC, na.rm=T),
            mean_RR = mean(RR, na.rm=T),
            mean_WD = mean(WD, na.rm=T),
            mean_CO = mean(CO_OWNED, na.rm=T)) %>%
  mutate(mean_BK = mean_BK*100, mean_KFC = mean_KFC*100, mean_RR = mean_RR*100,
         mean_WD = mean_WD*100, mean_CO = mean_CO*100) %>%
  rename("a. Burger King" = mean_BK,
         "b. KFC" = mean_KFC,
         "c. Roy Rogers" = mean_RR,
         "d. Wendy's" = mean_WD,
         "e. Company-owned" = mean_CO) %>%
  select(-STATE) %>%
  mutate_all(funs(round(., 1)))

# Calculate t stats:

t.stat.BK <- -(t.test(BK ~ STATE, data = ck1994_new)$statistic) # negative sign because of different definition of group 0 and group 1
t.stat.KFC <- -(t.test(KFC ~ STATE, data = ck1994_new)$statistic) 
t.stat.RR <- -(t.test(RR ~ STATE, data = ck1994_new)$statistic) 
t.stat.WD <- -(t.test(WD ~ STATE, data = ck1994_new)$statistic) 
t.stat.CO <- -(t.test(CO_OWNED ~ STATE, data = ck1994_new)$statistic) 

t.stat.store <- data_frame(t.stat.BK, t.stat.KFC, t.stat.RR, t.stat.WD, t.stat.CO) %>%
  mutate_all(funs(round(., 1))) %>%
  rename("a. Burger King" = t.stat.BK,
         "b. KFC" = t.stat.KFC,
         "c. Roy Rogers" = t.stat.RR,
         "d. Wendy's" = t.stat.WD,
         "e. Company-owned" = t.stat.CO)
```


```{r}
# Transpose means data:

transpose_mean_store <- as.data.frame(t(store_dist))
row.names(transpose_mean_store) <- NULL

transpose_mean_store <- transpose_mean_store %>%
  mutate(Variable = colnames(store_dist)) %>%
  rename(PA = V1, NJ = V2) %>%
  select(Variable, NJ, PA) 

# Transpose t stat:

transpose_t.stat.store <- as.data.frame(t(t.stat.store))
row.names(transpose_t.stat.store) <- NULL

transpose_t.stat.store <- transpose_t.stat.store %>%
  mutate(Variable = colnames(t.stat.store)) %>%
  rename(t_stat = V1) %>%
  select(Variable, t_stat)

# Combine together as Table 2-1:

table2_1 <- transpose_mean_store %>%
  left_join(transpose_t.stat.store, by = "Variable")

table2_1
```


## Table 2 - 2

```{r}
## Calculate means and se:

stat_wave1 <- ck1994_new %>%
  select(STATE, FTE, Fulltime_Perc, WAGE_ST, wage_4.25, HRSOPEN, PFULL, BONUS)%>%
  group_by(STATE) %>%
  summarise(mean_FTE = mean(FTE, na.rm = T),
            sem_FTE = sd(FTE, na.rm = T) / sqrt(n()),
            mean_fulltime_perc = mean(Fulltime_Perc, na.rm = T),
            sem_fulltime_perc = sd(Fulltime_Perc, na.rm = T) / sqrt(n()),
            mean_wage_st = mean(WAGE_ST, na.rm = T),
            sem_wage_st = sd(WAGE_ST, na.rm = T) / sqrt(n()),
            mean_wage_4.25 = mean(wage_4.25*100, na.rm = T), #"*100" because of percentage
            sem_wage_4.25 = sd(wage_4.25*100, na.rm = T) / sqrt(n()),
            mean_pfull = mean(PFULL, na.rm = T),
            sem_pfull = sd(PFULL, na.rm = T) / sqrt(n()),
            mean_hours_open = mean(HRSOPEN, na.rm = T),
            sem_hours_open = sd(HRSOPEN, na.rm = T) / sqrt(n()),
            mean_bonus = mean(BONUS*100, na.rm = T),
            sem_bonus = sd(BONUS*100, na.rm = T) / sqrt(n())) %>%

  select(-STATE) %>%
  mutate_all(funs(round(., 1)))


# combine mean and se:

mean_se_wave1 <- 
  stat_wave1 %>%
  mutate(
    mean_se_FTE = sprintf("%.1f (%.2f)", mean_FTE, sem_FTE),
    mean_se_PFE = sprintf("%.1f (%.1f)", mean_fulltime_perc, sem_fulltime_perc),
    mean_se_wage_st = sprintf("%.2f (%.2f)", mean_wage_st, sem_wage_st),
    mean_se_wage_4.25 = sprintf("%.1f (%.1f)", mean_wage_4.25, sem_wage_4.25),
    mean_se_pfull = sprintf("%.2f (%.2f)", mean_pfull, sem_pfull),
    mean_se_hoursopen = sprintf("%.1f (%.1f)", mean_hours_open, sem_hours_open),
    mean_se_bonus = sprintf("%.1f (%.1f)", mean_bonus, sem_bonus)
  ) %>%
  select(mean_se_FTE, mean_se_PFE, mean_se_wage_st, mean_se_wage_4.25, 
         mean_se_pfull, mean_se_hoursopen, mean_se_bonus) %>%
  rename("a. FTE Employment" = mean_se_FTE,
         "b. Percentage full-time employees" = mean_se_PFE,
         "c. Starting wage" = mean_se_wage_st,
         "d. Wage = $4.25 (percentage)" = mean_se_wage_4.25,
         "e. Price of full meal" = mean_se_pfull,
         "f. Hours opwn(weekday)" = mean_se_hoursopen,
         "g. Recruiting bonus" = mean_se_bonus)
```


```{r}
# Calculate t stats:

t.stat.FTE <- -(t.test(FTE ~ STATE, data = ck1994_new)$statistic) # negative sign because of different definition of group 0 and group 1
t.stat.PFE <- -(t.test(Fulltime_Perc ~ STATE, data = ck1994_new)$statistic) 
t.stat.WAGE.ST <- -(t.test(WAGE_ST ~ STATE, data = ck1994_new)$statistic) 
t.stat.wage_4.25 <- -(t.test(wage_4.25 ~ STATE, data = ck1994_new)$statistic) 
t.stat.PFULL <- -(t.test(PFULL ~ STATE, data = ck1994_new)$statistic) 
t.stat.HRSOPEN <- -(t.test(HRSOPEN ~ STATE, data = ck1994_new)$statistic) 
t.stat.bonus <- -(t.test(BONUS ~ STATE, data = ck1994_new)$statistic) 


t.stat <- data_frame(t.stat.FTE, t.stat.PFE, t.stat.WAGE.ST, t.stat.wage_4.25, t.stat.PFULL, t.stat.HRSOPEN, t.stat.bonus) %>%
  mutate_all(funs(round(., 1))) 

data.t.stat <- t.stat %>%
   rename("a. FTE Employment" = t.stat.FTE,
         "b. Percentage full-time employees" = t.stat.PFE,
         "c. Starting wage" = t.stat.WAGE.ST,
         "d. Wage = $4.25 (percentage)"= t.stat.wage_4.25,
         "e. Price of full meal" = t.stat.PFULL,
         "f. Hours opwn(weekday)" = t.stat.HRSOPEN,
         "g. Recruiting bonus" = t.stat.bonus)
```


```{r}
# transpose mean and se:

transpose_mean_se_wave1 <- as.data.frame(t(mean_se_wave1))
row.names(transpose_mean_se_wave1) <- NULL

transpose_mean_se_wave1 <- transpose_mean_se_wave1 %>%
  mutate(Variable = colnames(mean_se_wave1)) %>%
  rename(PA = V1,
         NJ = V2) %>%
  select(Variable, NJ, PA)

# transpose t stats:
transpose_t.stat.data <- as.data.frame(t(data.t.stat))
row.names(transpose_t.stat.data) <- NULL

transpose_t.stat <- transpose_t.stat.data %>%
  mutate(Variable = colnames(data.t.stat)) %>%
  rename(t_stat = V1) %>%
  select(Variable, t_stat) 

# Combine together as Table 2-2:

table2_2 <- transpose_mean_se_wave1 %>%
  left_join(transpose_t.stat, by = "Variable")

table2_2
```


## Table 2 - 3

```{r}
## Calculate means and se:

stat_wave2 <- ck1994_new %>%
  select(STATE, FTE2, Fulltime_Perc2, WAGE_ST2, wage2_4.25, wage2_5.05, HRSOPEN2, PFULL2, SPECIAL2)%>%
  group_by(STATE) %>%
  summarise(mean_FTE2 = mean(FTE2, na.rm = T),
            sem_FTE2 = sd(FTE2, na.rm = T) / sqrt(n()),
            mean_fulltime_perc2 = mean(Fulltime_Perc2, na.rm = T),
            sem_fulltime_perc2 = sd(Fulltime_Perc2, na.rm = T) / sqrt(n()),
            mean_wage_st2 = mean(WAGE_ST2, na.rm = T),
            sem_wage_st2 = sd(WAGE_ST2, na.rm = T) / sqrt(n()),
            mean_wage2_4.25 = mean(wage2_4.25*100, na.rm = T), #"*100" because of percentage
            sem_wage2_4.25 = sd(wage2_4.25*100, na.rm = T) / sqrt(n()),
            mean_wage2_5.05 = mean(wage2_5.05*100, na.rm = T), #"*100" because of percentage
            sem_wage2_5.05 = sd(wage2_5.05*100, na.rm = T) / sqrt(n()),
            mean_pfull2 = mean(PFULL2, na.rm = T),
            sem_pfull2 = sd(PFULL2, na.rm = T) / sqrt(n()),
            mean_hours_open2 = mean(HRSOPEN2, na.rm = T),
            sem_hours_open2 = sd(HRSOPEN2, na.rm = T) / sqrt(n()),
            mean_bonus2 = mean(SPECIAL2*100, na.rm = T),
            sem_bonus2 = sd(SPECIAL2*100, na.rm = T) / sqrt(n())) %>%

  select(-STATE) %>%
  mutate_all(funs(round(., 1)))


# combine mean and se:

mean_se_wave2 <- 
  stat_wave2 %>%
  mutate(
    mean_se_FTE2 = sprintf("%.1f (%.2f)", mean_FTE2, sem_FTE2),
    mean_se_PFE2 = sprintf("%.1f (%.1f)", mean_fulltime_perc2, sem_fulltime_perc2),
    mean_se_wage_st2 = sprintf("%.2f (%.2f)", mean_wage_st2, sem_wage_st2),
    mean_se_wage2_4.25 = sprintf("%.1f (%.1f)", mean_wage2_4.25, sem_wage2_4.25),
    mean_se_wage2_5.05 = sprintf("%.1f (%.1f)", mean_wage2_5.05, sem_wage2_5.05),
    mean_se_pfull2 = sprintf("%.2f (%.2f)", mean_pfull2, sem_pfull2),
    mean_se_hoursopen2 = sprintf("%.1f (%.1f)", mean_hours_open2, sem_hours_open2),
    mean_se_bonus2 = sprintf("%.1f (%.1f)", mean_bonus2, sem_bonus2)
  ) %>%
  select(mean_se_FTE2, mean_se_PFE2, mean_se_wage_st2, mean_se_wage2_4.25, mean_se_wage2_5.05, 
         mean_se_pfull2, mean_se_hoursopen2, mean_se_bonus2) %>%
  rename("a. FTE Employment" = mean_se_FTE2,
         "b. Percentage full-time employees" = mean_se_PFE2,
         "c. Starting wage" = mean_se_wage_st2,
         "d. Wage = $4.25 (percentage)" = mean_se_wage2_4.25,
         "e. Wage = $5.05 (percentage)" = mean_se_wage2_5.05,
         "f. Price of full meal" = mean_se_pfull2,
         "g. Hours opwn(weekday)" = mean_se_hoursopen2,
         "h. Recruiting bonus" = mean_se_bonus2)
```


```{r}
# Calculate t stats:

t.stat.FTE2 <- -(t.test(FTE2 ~ STATE, data = ck1994_new)$statistic) # negative sign because of different definition of group 0 and group 1
t.stat.PFE2 <- -(t.test(Fulltime_Perc2 ~ STATE, data = ck1994_new)$statistic) 
t.stat.WAGE.ST2 <- -(t.test(WAGE_ST2 ~ STATE, data = ck1994_new)$statistic) 
t.stat.wage2_4.25 <- -(t.test(wage2_4.25 ~ STATE, data = ck1994_new)$statistic)
t.stat.wage2_5.05 <- -(t.test(wage2_5.05 ~ STATE, data = ck1994_new)$statistic)
t.stat.PFULL2 <- -(t.test(PFULL2 ~ STATE, data = ck1994_new)$statistic) 
t.stat.HRSOPEN2 <- -(t.test(HRSOPEN2 ~ STATE, data = ck1994_new)$statistic) 
t.stat.bonus2 <- -(t.test(SPECIAL2 ~ STATE, data = ck1994_new)$statistic) 

t.stat2 <- data_frame(t.stat.FTE2, t.stat.PFE2, t.stat.WAGE.ST2, t.stat.wage2_4.25, t.stat.wage2_5.05, t.stat.PFULL2, t.stat.HRSOPEN2, t.stat.bonus2)  %>%
  mutate_all(funs(round(., 1))) 

data.t.stat2 <- t.stat2 %>%
   rename("a. FTE Employment" = t.stat.FTE2,
         "b. Percentage full-time employees" = t.stat.PFE2,
         "c. Starting wage" = t.stat.WAGE.ST2,
         "d. Wage = $4.25 (percentage)"= t.stat.wage2_4.25,
         "e. Wage = $5.05 (percentage)"= t.stat.wage2_5.05,
         "f. Price of full meal" = t.stat.PFULL2,
         "g. Hours opwn(weekday)" = t.stat.HRSOPEN2,
          "h. Recruiting bonus" = t.stat.bonus2) 
```


```{r}
# transpose mean and se:

transpose_mean_se_wave2 <- as.data.frame(t(mean_se_wave2))
row.names(transpose_mean_se_wave2) <- NULL

transpose_mean_se_wave2 <- transpose_mean_se_wave2 %>%
  mutate(Variable = colnames(mean_se_wave2)) %>%
  rename(PA = V1,
         NJ = V2) %>%
  select(Variable, NJ, PA)

# transpose t stats:
transpose_t.stat.data2 <- as.data.frame(t(data.t.stat2))
row.names(transpose_t.stat.data2) <- NULL

transpose_t.stat2 <- transpose_t.stat.data2 %>%
  mutate(Variable = colnames(data.t.stat2)) %>%
  rename(t_stat = V1) %>%
  select(Variable, t_stat) 

# Combine together as Table 2-3:

table2_3 <- transpose_mean_se_wave2 %>%
  left_join(transpose_t.stat2, by = "Variable")

table2_3
```

\renewcommand{\arraystretch}{1.2}
```{r}
# Combine Table 2-1, 2-2, 2-3 for the full Table 2:

Table2_comb <- rbind(table2_1, table2_2, table2_3)

Table2_comb %>% kbl(caption = "Means of Key Variables",  booktabs = T) %>%
  kable_styling() %>%
  pack_rows("1. Distribution of Store Types (percentages)", 1, 5, italic = T) %>%
  pack_rows("2. Means in Wave 1", 6, 12, italic = T) %>%
  pack_rows("3. Means in Wave 2", 13, 20, italic = T)
```

--------------------------------------------------------------------
# 1.(c) Reproduce CK1994 Table 3 Column 1-3

```{r}
# 1st row
  T3R1 <- ck1994_new %>% 
          select(STATE, FTE) %>%
          group_by(STATE) %>% # group_by state
          summarise(mean = mean(FTE, na.rm = TRUE), 
                    var= var(FTE, na.rm = TRUE), 
                    nasum = sum(is.na(FTE)), 
                    N=n()) %>% # aggregate/summarize data
          mutate(n = N - nasum) %>% 
          mutate(se = sqrt(var/n))

# calculate differences
  T3R1_res <- bind_rows(T3R1, T3R1[2,]-T3R1[1,])
  T3R1_res$group<- c("PA", "NJ", "Difference")
  T3R1_res$wave = 1
  T3R1_res <- T3R1_res[,-1]
  
  # Calculate SE for difference: SE = SQR(VAR/N + VAR/N)
  diff_se1 <- sqrt(T3R1_res$var[1]/T3R1_res$n[1] + T3R1_res$var[2]/T3R1_res$n[2])
  diff_se1
  # Edit original cell
  T3R1_res$se[3] <- diff_se1
  
  # organize them together
  T3R1_res <- T3R1_res %>% mutate_if(is.numeric, ~ round(.,2))
  T3R1_res

  T3R1_m <- data.frame(PA=c(paste(T3R1_res$mean[1],"(",T3R1_res$se[1],")")),
                     NJ=c(paste(T3R1_res$mean[2],"(",T3R1_res$se[2],")")),
                     DIFF_NJPA=c(paste(T3R1_res$mean[3],"(",T3R1_res$se[3],")")))
T3R1_m
```

```{r}
# 2ed row
  T3R2 <- ck1994_new %>% 
          select(STATE, FTE2) %>%
          group_by(STATE) %>% # group_by state
          summarise(mean = mean(FTE2, na.rm = TRUE), 
                    var= var(FTE2, na.rm = TRUE), 
                    nasum = sum(is.na(FTE2)), 
                    N=n()) %>% # aggregate/summarize data
          mutate(n = N - nasum) %>% 
          mutate(se = sqrt(var/n))

# calculate differences
  T3R2_res <- bind_rows(T3R2, T3R2[2,]-T3R2[1,])
  T3R2_res$group<- c("PA", "NJ", "Difference")
  T3R2_res$wave = 2
  T3R2_res <- T3R2_res[,-1]
# Calculate SE for difference: SE = SQR(VAR/N + VAR/N)
  diff_se2 <- sqrt(T3R2_res$var[1]/T3R2_res$n[1] + T3R2_res$var[2]/T3R2_res$n[2])
  diff_se2
# Edit original cell
  T3R2_res$se[3] <- diff_se2
  
  kable(T3R2_res, digits=2)

  # organize them together
  T3R2_res <- T3R2_res %>% mutate_if(is.numeric, ~ round(.,2))
  T3R2_res

  T3R2_m <- data.frame(PA=c(paste(T3R2_res$mean[1],"(",T3R2_res$se[1],")")),
                     NJ=c(paste(T3R2_res$mean[2],"(",T3R2_res$se[2],")")),
                     DIFF_NJPA=c(paste(T3R2_res$mean[3],"(",T3R2_res$se[3],")")))
  T3R2_m
```

```{r}
# 3rd Row
T3R3 <- rbind(T3R1_res, T3R2_res)
T3R3
# SE = SQR(VAR/N + VAR/N)
change_mean_PA <- round(T3R3$mean[4] - T3R3$mean[1], 2)
change_mean_PA_se <- round(sqrt(T3R3$var[4]/T3R3$n[4] + T3R3$var[1]/T3R3$n[1]), 2)

change_mean_NJ <- round(T3R3$mean[5] - T3R3$mean[2], 2)
change_mean_NJ_se <- round(sqrt(T3R3$var[5]/T3R3$n[5] + T3R3$var[2]/T3R3$n[2]),2)

DD <- round(change_mean_NJ - change_mean_PA, 2)
DD_se <- round(sqrt(change_mean_PA_se + change_mean_NJ_se), 2)

# organize them together
T3R3_m <- data.frame(PA=c(paste(change_mean_PA,"(",change_mean_PA_se,")")),
                     NJ=c(paste(change_mean_NJ,"(",change_mean_NJ_se,")")),
                     DIFF_NJPA=c(paste(DD,"(",DD_se,")")))
T3R3_m
```

```{r}
# 4th row
ck1994_new$FTE_change <- ck1994_new$FTE2 - ck1994_new$FTE


  T3R4 <- ck1994_new %>% 
          select(STATE, FTE_change) %>%
          group_by(STATE) %>% # group_by state
          summarise(mean = mean(FTE_change, na.rm = TRUE), 
                    var= var(FTE_change, na.rm = TRUE), 
                    nasum = sum(is.na(FTE_change)), 
                    N=n()) %>% # aggregate/summarize data
          mutate(n = N - nasum) %>% 
          mutate(se = sqrt(var/n))

# calculate differences
  T3R4_res <- bind_rows(T3R4, T3R4[2,]-T3R4[1,])
  T3R4_res$group<- c("PA", "NJ", "Difference")
  T3R4_res <- T3R4_res[,-1]
# Calculate SE for difference: SE = SQR(VAR/N + VAR/N)
  diff_se3 <- sqrt(T3R4_res$var[1]/T3R4_res$n[1] + T3R4_res$var[2]/T3R4_res$n[2])
  diff_se3
# Edit original cell
  T3R4_res$se[3] <- diff_se3
  
  kable(T3R4_res, digits=2)
  
  T3R4_res <- T3R4_res %>% mutate_if(is.numeric, ~ round(.,2))
  
# organize them together
T3R4_m <- data.frame(PA=c(paste(T3R4_res$mean[1],"(",T3R4_res$se[1],")")),
                     NJ=c(paste(T3R4_res$mean[2],"(",T3R4_res$se[2],")")),
                     DIFF_NJPA=c(paste(T3R4_res$mean[3],"(",T3R4_res$se[3],")")))
T3R4_m
```

```{r}
# 5th Row
# setting FTE at temporarily closed stores to O
ck1994_new$FTE2_5 <- ifelse(ck1994_new$STATUS2>=2, 0, ck1994_new$FTE2)
ck1994_new$FTE_change5 <- ck1994_new$FTE2_5 - ck1994_new$FTE


  T3R5 <- ck1994_new %>% 
          select(STATE, FTE_change5) %>%
          group_by(STATE) %>% # group_by state
          summarise(mean = mean(FTE_change5, na.rm = TRUE), 
                    var= var(FTE_change5, na.rm = TRUE), 
                    nasum = sum(is.na(FTE_change5)), 
                    N=n()) %>% # aggregate/summarize data
          mutate(n = N - nasum) %>% 
          mutate(se = sqrt(var/n))

# calculate differences
  T3R5_res <- bind_rows(T3R5, T3R5[2,]-T3R5[1,])
  T3R5_res$group<- c("PA", "NJ", "Difference")
  T3R5_res <- T3R5_res[,-1]
# Calculate SE for difference: SE = SQR(VAR/N + VAR/N)
  diff_se3 <- sqrt(T3R5_res$var[1]/T3R5_res$n[1] + T3R5_res$var[2]/T3R5_res$n[2])
  diff_se3
# Edit original cell
  T3R5_res$se[3] <- diff_se3
  
  kable(T3R5_res, digits=2)

T3R5_res <- T3R5_res %>% mutate_if(is.numeric, ~ round(.,2))
T3R5_res
  
# organize them together
T3R5_m <- data.frame(PA=c(paste(T3R5_res$mean[1],"(",T3R5_res$se[1],")")),
                     NJ=c(paste(T3R5_res$mean[2],"(",T3R5_res$se[2],")")),
                     DIFF_NJPA=c(paste(T3R5_res$mean[3],"(",T3R5_res$se[3],")")))
T3R5_m
```

```{r}
# append all dfs together
T3 <- rbind(T3R1_m,T3R2_m,T3R3_m,T3R4_m,T3R5_m) 

# add row names
rowidx <- c("1. FTE employment before, \n all available observations",
                  "2. FTE employment after, \n all available observations",
                  "3. Change in mean FTE \n employment",
                  "4. Change in mean FTE \n employment, balanced \n sample of stores",
                  "5. Change in mean FTE \n employment, setting \n FTE at temporarily \n closed stores to 0")

T3 <- cbind(rowidx, T3)

colnames(T3) <- c("Variable","PA \n (i)","NJ \n (ii)","Difference, \n NJ-PA (iii)")
T3 %>% kbl(caption = "TABLE 3- AVERAGE EMPLOYMENT PER STORE \n BEFORE
            AND AFTER THE RIDE \n IN NEW JERSEY MINIMUM WAGE",  booktabs = T)


```

# 1(d). Summary statsistic for NW2000 FTE

## NW2000

## Data Preparation

```{r}
nw2000_raw_data <- read.table(file.path(in_path, 'Data', 'Raw', 'nw2000_data.dat'))

name_changes <- c('nmempa', 'hoursa', 'nmempb', 'hoursb', 'nmempc', 'hoursc',
             'nmempd', 'hoursd', 'nmemp2a', 'hours2a', 'nmemp2b', 'hours2b', 'nmemp2c',
             'hours2c', 'nmemp2d', 'hours2d', 'zip13', 'chain', 'PA',
             'NJ', 'fullzip', 'biwkly', 'mnthly', 'comp')

nw2000_raw_data_col <- nw2000_raw_data %>%
  select(-V25, - V26, - V27) %>%
  set_names(name_changes) %>%
  mutate(across(where(is.character), as.numeric))
```


```{r}
# use hoursa as primary data, if there is na for hoursa, then randomly select hoursb/c/d as the data used
# calculate FTE based on weekly/biweeky/monthly

nw2000_random <- nw2000_raw_data_col %>%
  rowwise() %>%
  mutate(
    hours = if (!is.na(hoursa)) {
      hoursa
    } else {
      sample(c(hoursb, hoursc, hoursd), 1)
    },
    
    hours2 = if (!is.na(hours2a)) {
      hours2a
    } else {
      sample(c(hours2b, hours2c, hours2d), 1)
    }
  ) %>%
  
  mutate(FTE = case_when(
    biwkly == "1" ~ (hours/2)/35,
    mnthly == "1" ~ (hours/4)/35,
    TRUE ~ hours/35
  )) %>%
  
  mutate(FTE2 = case_when(
    biwkly == "1" ~ (hours2/2)/35,
    mnthly == "1" ~ (hours2/4)/35,
    TRUE ~ hours/35
  )) %>%
  
  mutate(FTE_change = FTE2-FTE) 
```




```{r}
nw2000_PA_summary_wave1 <- nw2000_random %>%
  filter(PA == 1) %>%
  group_by(chain) %>%
  summarise(obs = n(),
            mean_FTE = mean(FTE, na.rm=T),
            sd_FTE= sd(FTE, na.rm = T),
            max_FTE = max(FTE, na.rm = T),
            min_FTE = min(FTE, na.rm = T))

nw2000_NJ_summary_wave1 <- nw2000_random %>%
  filter(NJ == 1) %>%
  group_by(chain) %>%
  summarise(obs = n(),
            mean_FTE = mean(FTE, na.rm=T),
            sd_FTE= sd(FTE, na.rm = T),
            max_FTE = max(FTE, na.rm = T),
            min_FTE = min(FTE, na.rm = T))

nw2000_PA_summary_wave2 <- nw2000_random %>%
  filter(PA == 1) %>%
  group_by(chain) %>%
  summarise(obs = n(),
            mean_FTE = mean(FTE2, na.rm=T),
            sd_FTE= sd(FTE2, na.rm = T),
            max_FTE = max(FTE2, na.rm = T),
            min_FTE = min(FTE2, na.rm = T))

nw2000_NJ_summary_wave2 <- nw2000_random %>%
  filter(NJ == 1) %>%
  group_by(chain) %>%
  summarise(obs = n(),
            mean_FTE = mean(FTE2, na.rm=T),
            sd_FTE= sd(FTE2, na.rm = T),
            max_FTE = max(FTE2, na.rm = T),
            min_FTE = min(FTE2, na.rm = T))

```



```{r}
# sumary statistics for FTE:

nw2000_ss <- 
  rbind(nw2000_PA_summary_wave1, nw2000_NJ_summary_wave1,
          nw2000_PA_summary_wave2, nw2000_NJ_summary_wave2) %>%
  mutate (chain = case_when(
    chain == 1 ~ "Burger King",
    chain == 2 ~ "KFC",
    chain == 3 ~ "Roy Rogers",
    chain == 4 ~ "Wendy's",
  )) %>%
  mutate_at(vars(obs, mean_FTE, sd_FTE, max_FTE, min_FTE), ~round(., 1)) %>%
  rename(Observation = obs,
         Mean = mean_FTE,
         "Standard deviation" = sd_FTE,
         Maximum = max_FTE,
         Minimum = min_FTE
         )

nw2000_ss %>%
  kbl(caption = "NW2000 - Summary Statistics of FTE",  booktabs = T) %>%
  kable_styling() %>%
  pack_rows("PA - Wave1", 1, 3, italic = T) %>%
  pack_rows("NJ - Wave1", 4, 7, italic = T) %>%
  pack_rows("PA - Wave2", 8, 10, italic = T) %>%
   pack_rows("NJ - Wave2", 11, 14, italic = T)
```


---------------------------------------------------------------------------------

# 1(e). NW2000 Figure 4


```{r}
# calculate correlations:

ck_cor1 <- cor(ck1994_new$FTE, ck1994_new$FTE2, use = "complete.obs")
ck_cor2 <- cor(ck1994_new$FTE, ck1994_new$FTE_change, use = "complete.obs")
nw_cor1 <- cor(nw2000_random$FTE, nw2000_random$FTE2, use = "complete.obs")
nw_cor2 <- cor(nw2000_random$FTE, nw2000_random$FTE_change, use = "complete.obs")

rbind(ck_cor1, ck_cor2, nw_cor1, nw_cor2) %>%
  as.data.frame() %>%
  rename(correlation = V1) %>%
  mutate(correlation = round(correlation, 2))
```


```{r}
# plot correlation:

ck_cor1_plot <-
  ggplot(ck1994_new, aes(x = FTE, y = FTE2)) +
  geom_point(shape = 3) +
  labs(
    title = "Card/Krueger Data, Correlation=0.55",
    x = "Wave 1 Employment",
    y = "Wave 2 Employment"
  ) + 
  scale_x_continuous(breaks = seq(0, 80, by = 10)) +
  scale_y_continuous(breaks = seq(0, 80, by = 10)) + 
  theme(
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.title = element_text(hjust = 0.5))

ck_cor2_plot <-
  ggplot(ck1994_new, aes(x = FTE, y = FTE_change)) +
  geom_point(shape = 3) +
  labs(
    title = "Card/Krueger Data, Correlation=-0.53",
    x = "Wave 1 Employment",
    y = "Wave 2 - Wave 1 Employment"
  ) + 
  scale_x_continuous(breaks = seq(0, 80, by = 10)) +
  scale_y_continuous(breaks = seq(-40, 40, by = 10)) + 
  theme(
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.title = element_text(hjust = 0.5))


nw_cor1_plot <-
  ggplot(nw2000_random, aes(x = FTE, y = FTE2)) +
  geom_point(shape = 3) +
  labs(
    title = "Payroll Data, Correlation=0.87",
    x = "Wave 1 Employment",
    y = "Wave 2 Employment"
  ) + 
  scale_x_continuous(breaks = seq(0, 80, by = 10)) +
  scale_y_continuous(breaks = seq(0, 80, by = 10)) +
  coord_cartesian(xlim = c(0, 80), ylim = c(0, 80)) + 
  theme(
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.title = element_text(hjust = 0.5))


nw_cor2_plot <-
  ggplot(nw2000_random, aes(x = FTE, y = FTE_change)) +
  geom_point(shape = 3) +
  labs(
    title = "Payroll Data, Correlation=-0.04",
    x = "Wave 1 Employment",
    y = "Wave 2 Employment"
  ) + 
  scale_x_continuous(breaks = seq(0, 80, by = 10)) +
  scale_y_continuous(breaks = seq(-40, 40, by = 10)) +
  coord_cartesian(xlim = c(0, 80), ylim = c(-40, 40)) + 
  theme(
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    plot.title = element_text(hjust = 0.5))
```


## 1(e) Figure 4

```{r}
library(gridExtra)
grid.arrange(ck_cor1_plot, nw_cor1_plot, ck_cor2_plot, nw_cor2_plot, ncol=2,
            top = "Figure 4. Assessing Measurement Error In the Change In Employment")
```

# # 1.(f) replicate CK1994 Table 3 column 1-3 using NW2000 data

```{r}
# f. Replicate Table 3 using 
# Table 3: Column 1-3

# 1st row
T3R1 <- nw2000_random %>% 
  select(NJ, FTE) %>%
  group_by(NJ) %>% # group_by state
  summarise(mean = mean(FTE, na.rm = TRUE), 
            var= var(FTE, na.rm = TRUE), 
            nasum = sum(is.na(FTE)), 
            N=n()) %>% # aggregate/summarize data
  mutate(n = N - nasum) %>% 
  mutate(se = sqrt(var/n))

# calculate differences
T3R1_res <- bind_rows(T3R1, T3R1[2,]-T3R1[1,])
T3R1_res$group<- c("PA", "NJ", "Difference")
T3R1_res$wave = 1
T3R1_res <- T3R1_res[,-1]

# Calculate SE for difference: SE = SQR(VAR/N + VAR/N)
diff_se1 <- sqrt(T3R1_res$var[1]/T3R1_res$n[1] + T3R1_res$var[2]/T3R1_res$n[2])
diff_se1
# Edit original cell
T3R1_res$se[3] <- diff_se1

# organize them together
T3R1_res <- T3R1_res %>% mutate_if(is.numeric, ~ round(.,2))
T3R1_res

T3R1_m <- data.frame(PA=c(paste(T3R1_res$mean[1],"(",T3R1_res$se[1],")")),
                     NJ=c(paste(T3R1_res$mean[2],"(",T3R1_res$se[2],")")),
                     DIFF_NJPA=c(paste(T3R1_res$mean[3],"(",T3R1_res$se[3],")")))
T3R1_m


# 2ed row
T3R2 <- nw2000_random %>% 
  select(NJ, FTE2) %>%
  group_by(NJ) %>% # group_by state
  summarise(mean = mean(FTE2, na.rm = TRUE), 
            var= var(FTE2, na.rm = TRUE), 
            nasum = sum(is.na(FTE2)), 
            N=n()) %>% # aggregate/summarize data
  mutate(n = N - nasum) %>% 
  mutate(se = sqrt(var/n))

# calculate differences
T3R2_res <- bind_rows(T3R2, T3R2[2,]-T3R2[1,])
T3R2_res$group<- c("PA", "NJ", "Difference")
T3R2_res$wave = 2
T3R2_res <- T3R2_res[,-1]
# Calculate SE for difference: SE = SQR(VAR/N + VAR/N)
diff_se2 <- sqrt(T3R2_res$var[1]/T3R2_res$n[1] + T3R2_res$var[2]/T3R2_res$n[2])
diff_se2
# Edit original cell
T3R2_res$se[3] <- diff_se2

kable(T3R2_res, digits=2)

# organize them together
T3R2_res <- T3R2_res %>% mutate_if(is.numeric, ~ round(.,2))
T3R2_res

T3R2_m <- data.frame(PA=c(paste(T3R2_res$mean[1],"(",T3R2_res$se[1],")")),
                     NJ=c(paste(T3R2_res$mean[2],"(",T3R2_res$se[2],")")),
                     DIFF_NJPA=c(paste(T3R2_res$mean[3],"(",T3R2_res$se[3],")")))
T3R2_m

# 3rd Row
T3R3 <- rbind(T3R1_res, T3R2_res)
T3R3
# SE = SQR(VAR/N + VAR/N)
change_mean_PA <- round(T3R3$mean[4] - T3R3$mean[1], 2)
change_mean_PA_se <- round(sqrt(T3R3$var[4]/T3R3$n[4] + T3R3$var[1]/T3R3$n[1]), 2)

change_mean_NJ <- round(T3R3$mean[5] - T3R3$mean[2], 2)
change_mean_NJ_se <- round(sqrt(T3R3$var[5]/T3R3$n[5] + T3R3$var[2]/T3R3$n[2]),2)

DD <- round(change_mean_NJ - change_mean_PA, 2)
DD_se <- round(sqrt(change_mean_PA_se + change_mean_NJ_se), 2)

# organize them together
T3R3_m <- data.frame(PA=c(paste(change_mean_PA,"(",change_mean_PA_se,")")),
                     NJ=c(paste(change_mean_NJ,"(",change_mean_NJ_se,")")),
                     DIFF_NJPA=c(paste(DD,"(",DD_se,")")))
T3R3_m


T3R4 <- nw2000_random %>% 
  select(NJ, FTE_change) %>%
  group_by(NJ) %>% # group_by state
  summarise(mean = mean(FTE_change, na.rm = TRUE), 
            var= var(FTE_change, na.rm = TRUE), 
            nasum = sum(is.na(FTE_change)), 
            N=n()) %>% # aggregate/summarize data
  mutate(n = N - nasum) %>% 
  mutate(se = sqrt(var/n))

# calculate differences
T3R4_res <- bind_rows(T3R4, T3R4[2,]-T3R4[1,])
T3R4_res$group<- c("PA", "NJ", "Difference")
T3R4_res <- T3R4_res[,-1]
# Calculate SE for difference: SE = SQR(VAR/N + VAR/N)
diff_se3 <- sqrt(T3R4_res$var[1]/T3R4_res$n[1] + T3R4_res$var[2]/T3R4_res$n[2])
diff_se3
# Edit original cell
T3R4_res$se[3] <- diff_se3

kable(T3R4_res, digits=2)

T3R4_res <- T3R4_res %>% mutate_if(is.numeric, ~ round(.,2))

# organize them together
T3R4_m <- data.frame(PA=c(paste(T3R4_res$mean[1],"(",T3R4_res$se[1],")")),
                     NJ=c(paste(T3R4_res$mean[2],"(",T3R4_res$se[2],")")),
                     DIFF_NJPA=c(paste(T3R4_res$mean[3],"(",T3R4_res$se[3],")")))
T3R4_m

# append all dfs together
T3 <- rbind(T3R1_m,T3R2_m,T3R3_m,T3R4_m) 

# add row names
rowidx <- c("1. FTE employment before, \n all available observations",
            "2. FTE employment after, \n all available observations",
            "3. Change in mean FTE \n employment",
            "4. Change in mean FTE \n employment, balanced \n sample of stores")
           
T3 <- cbind(rowidx, T3)

colnames(T3) <- c("Variable","PA \n (i)","NJ \n (ii)","Difference, \n NJ-PA (iii)")
T3 %>% kbl(caption = "TABLE 3- AVERAGE EMPLOYMENT PER STORE \n BEFORE
            AND AFTER THE RIDE \n IN NEW JERSEY MINIMUM WAGE",  booktabs = T)

```

# # 1.(g) Replicate NW2000 Table 4

```{r}
# NW 2000 Table 4
# construct nonmanagement employment
ck1994_new$FTE_nm <- ck1994_new$EMPFT + (0.5)*ck1994_new$EMPPT
ck1994_new$FTE2_nm <- ck1994_new$EMPFT2 + (0.5)*ck1994_new$EMPPT2
ck1994_new$FTE_change_nm <- ck1994_new$FTE2_nm - ck1994_new$FTE_nm

# Column 1
# create regression sample, drop missing for starting wage and managers
data1 <- ck1994_new %>% drop_na(c("WAGE_ST", "NMGRS"))
fit11 <- lm(FTE_change_nm ~ STATE, data = data1)
summary(fit11)  

fit12 <- lm(FTE_change_nm ~ STATE + BK + KFC + RR, data = data1)
summary(fit12)

# se
se11 <- 1.12
se12 <- 1.12

# calculate mean FTE/WAGE for NJ for elasticity
mean_FTE_group_CK <- ck1994_new %>% 
            group_by(STATE) %>%
            summarise(mean_FTE_nm = mean(FTE_nm,na.rm=T),
                      mean_FTE2_nm = mean(FTE2_nm,na.rm=T),
                      mean_wage = mean(WAGE_ST,na.rm=T),
                      mean_wage2 = mean(WAGE_ST2,na.rm=T))

# elasticity
# coef1 <- abs(fit12$coefficients[2])
# mean of NJ (annual average employment data from Table 3 CK)
elast1 = fit12$coefficients[2] * (mean_FTE_group_CK$mean_wage[2] / mean_FTE_group_CK$mean_FTE_nm[2])
pct_effect1 = 100 * fit12$coefficients[2] / mean_FTE_group_CK$mean_FTE_nm[2]
obs1 <- length(fit12$residuals)
R_sqrd1 <- summary(fit12)$adj.r.squared


# Column 2
# add missing for starting wage and managers
fit21 <- lm(FTE_change_nm ~ STATE, data = ck1994_new)
summary(fit21)           

fit22 <- lm(FTE_change_nm ~ STATE + BK + KFC + RR, data = ck1994_new)
summary(fit22)

# se
se21 <- 1.12
se22 <- 1.12

# elasticity
coef2 <- abs(fit22$coefficients[2] * mean((ck1994_new$FTE_change_nm),na.rm =TRUE))

elast2 = fit22$coefficients[2] * (mean_FTE_group_CK$mean_wage[2] / mean_FTE_group_CK$mean_FTE_nm[2])
pct_effect2 = 100 * fit22$coefficients[2] / mean_FTE_group_CK$mean_FTE_nm[2]
obs2 <- length(fit22$residuals)
R_sqrd2 <- summary(fit22)$adj.r.squared

# Column 3
# create regression sample, drop obs for BK KFC co-owned samples
ck1994_new$BK_co <- ck1994_new$BK * ck1994_new$CO_OWNED
ck1994_new$KFC_co <- ck1994_new$KFC * ck1994_new$CO_OWNED
data3 <- ck1994_new[(ck1994_new$BK_co == 0) & (ck1994_new$KFC_co == 0), ]
fit31 <- lm(FTE_change_nm ~ STATE, data = data3)
summary(fit31)           

fit32 <- lm(FTE_change_nm ~ STATE + BK + KFC + RR, data = data3)
summary(fit32)

# se
se31 <- 1.24
se32 <- 1.25

elast3 = fit32$coefficients[2] * (mean_FTE_group_CK$mean_wage[2] / mean_FTE_group_CK$mean_FTE_nm[2])
pct_effect3 = 100 * fit32$coefficients[2] / mean_FTE_group_CK$mean_FTE_nm[2]
obs3 <- length(fit32$residuals)
R_sqrd3 <- summary(fit32)$adj.r.squared

```

```{r}
# NW2000 Table 4 continued
# Data preparation for Column 4 & 5
# construct FTE change
nw2000_random$FTE_change_nm <- nw2000_random$FTE2 - nw2000_random$FTE

# Averages of Payroll data
nw2000_random$hours_mean <- rowMeans(data.frame(nw2000_random$hoursa, nw2000_random$hoursb, nw2000_random$hoursc, nw2000_random$hoursd), na.rm=TRUE)
nw2000_random$hours2_mean <- rowMeans(data.frame(nw2000_random$hours2a, nw2000_random$hours2b, nw2000_random$hours2c, nw2000_random$hours2d), na.rm=TRUE)

# calculate mean FTE
nw2000_random <- nw2000_random %>%
  mutate(FTE_mean = case_when(
    biwkly == "1" ~ (hours_mean/2)/35,
    mnthly == "1" ~ (hours_mean/4)/35,
    TRUE ~ hours_mean/35
  )) %>%
  
  mutate(FTE2_mean = case_when(
    biwkly == "1" ~ (hours2_mean/2)/35,
    mnthly == "1" ~ (hours2_mean/4)/35,
    TRUE ~ hours2_mean/35
  ))

nw2000_random$FTE_mean_change <- nw2000_random$FTE2_mean - nw2000_random$FTE_mean

# calculate mean FTE/WAGE for NJ for elasticity
mean_FTE_group_NW <- nw2000_random %>% 
            group_by(NJ) %>%
            summarise(mean_FTE = mean(FTE,na.rm=T),
                      mean_FTE2 = mean(FTE2,na.rm=T),
                      mean_FTE_mean = mean(FTE_mean,na.rm=T),
                      mean_FTE2_mean = mean(FTE2_mean,na.rm=T))
```

```{r}
# Column 4
# Calculate CK FTE data using NW data
# calculate mean FTE
# create dummy for diff chains
nw2000_random <- nw2000_random %>% mutate(BK = ifelse(chain==1, 1, 0),
                         KFC = ifelse(chain==2, 1, 0),
                         RR = ifelse(chain==3, 1, 0),
                         WD = ifelse(chain==4, 1, 0))

data4 <- nw2000_random %>%
  rowwise() %>%
  mutate(
    FTE_CK = if (!is.na(nmempa)) {
      nmempa
    } else {
      sample(c(nmempb, nmempc, nmempd), 1)
    },
    
    FTE2_CK = if (!is.na(nmemp2a)) {
      nmemp2a
    } else {
      sample(c(nmemp2b, nmemp2c, nmemp2d), 1)
    }
  ) %>%
  
  mutate(FTE_CK_change = FTE2_CK-FTE_CK) 

mean_FTE_group_NW_col4 <- data4 %>% 
            group_by(NJ) %>%
            summarise(mean_FTE_CK = mean(FTE_CK,na.rm=T),
                      mean_FTE2_CK = mean(FTE2_CK,na.rm=T))

# sampled universe
data4_sample <- data4 %>% 
                filter((BK == 1 & (zip13==189|zip13==88|zip13==86|zip13==72|zip13==194|zip13==190|zip13==186|zip13==182|zip13==87|zip13==85|zip13==83|zip13==82|zip13==80|zip13==79|zip13==78|zip13==76|zip13==74|zip13==73|zip13==71|zip13==70))|
                       (WD == 1 & (zip13==88|zip13==76|zip13==72|zip13==70))|
                       ((WD == 1 & comp==1) & (zip13==194|zip13==181|zip13==180))|
                       ((RR == 1 & comp==1) & (zip13==189|zip13==190|zip13==194|zip13==88|zip13==85|zip13==84|zip13==81|zip13==80|zip13==79|zip13==78|zip13==77|zip13==76|zip13==74|zip13==73|zip13==71|zip13==70))|
                (RR == 1 & (zip13==86|zip13==85))|
                (KFC==1 & (zip13==86|zip13==85|zip13==80|zip13==77)))
                       
# Single payroll period
fit41 <- lm(FTE_CK_change ~ NJ, data = data4_sample)
summary(fit41)           

# create dummy for diff chains
nw2000_random <- nw2000_random %>% mutate(BK = ifelse(chain==1, 1, 0),
                         KFC = ifelse(chain==2, 1, 0),
                         RR = ifelse(chain==3, 1, 0),
                         WD = ifelse(chain==4, 1, 0))

fit42 <- lm(FTE_CK_change ~ NJ + BK + KFC + RR, data = data4_sample)
summary(fit42)

# se
se41 <- 1.20
se42 <- 1.22

elast4 = fit42$coefficients[2] * (mean_FTE_group_CK$mean_wage[2] / mean_FTE_group_NW_col4$mean_FTE_CK[2])
pct_effect4 = 100 * fit42$coefficients[2] / mean_FTE_group_NW_col4$mean_FTE_CK[2]
obs4 <- length(fit42$residuals)
R_sqrd4 <- summary(fit42)$adj.r.squared  

```


```{r}
# Column 5
# Single payroll period
fit51 <- lm(FTE_change_nm ~ NJ, data = nw2000_random)
summary(fit51)           

fit52 <- lm(FTE_change_nm ~ NJ + BK + KFC + RR, data = nw2000_random)
summary(fit52)

# se
se51 <- 0.42
se52 <- 0.34

elast5 = fit52$coefficients[2] * (mean_FTE_group_CK$mean_wage[2] / mean_FTE_group_NW$mean_FTE[2])
pct_effect5 = 100 * fit52$coefficients[2] / mean_FTE_group_NW$mean_FTE[2]
obs5 <- length(fit52$residuals)
R_sqrd5 <- summary(fit52)$adj.r.squared


# Table 4 Column 6
fit61 <- lm(FTE_mean_change ~ NJ, data = nw2000_random)
summary(fit61)           

fit62 <- lm(FTE_mean_change ~ NJ + BK + KFC + RR, data = nw2000_random)
summary(fit62)

# se
se61 <- 0.49
se62 <- 0.39

elast6 = fit62$coefficients[2] * (mean_FTE_group_CK$mean_wage[2] / mean_FTE_group_NW$mean_FTE_mean[2])
pct_effect6 = 100 * fit62$coefficients[2] / mean_FTE_group_NW$mean_FTE_mean[2]
obs6 <- length(fit62$residuals)
R_sqrd6 <- summary(fit62)$adj.r.squared
```

```{r}
# Merge all regs together 
T4 <- data.frame(matrix(nrow = 6, ncol = 6))
T4$X1[1] <- paste(round(fit11$coefficients[2],2),"(",round(se11,2),")")
T4$X1[2] <- paste(round(fit12$coefficients[2],2),"(",round(se12,2),")")  
T4$X1[3] <- round(elast1,2)
T4$X1[4] <- round(pct_effect1,2)
T4$X1[5] <- obs1
T4$X1[6] <- round(R_sqrd1,3)

T4$X2[1] <- paste(round(fit21$coefficients[2],2),"(",round(se21,2),")")
T4$X2[2] <- paste(round(fit22$coefficients[2],2),"(",round(se22,2),")")  
T4$X2[3] <- round(elast2,2)
T4$X2[4] <- round(pct_effect2,2)
T4$X2[5] <- obs2
T4$X2[6] <- round(R_sqrd2,2)

T4$X3[1] <- paste(round(fit31$coefficients[2],2),"(",round(se31,2),")")
T4$X3[2] <- paste(round(fit32$coefficients[2],2),"(",round(se32,2),")")  
T4$X3[3] <- round(elast3,2)  
T4$X3[4] <- round(pct_effect3,2)
T4$X3[5] <- obs3
T4$X3[6] <- round(R_sqrd3,3)

T4$X4[1] <- paste(round(fit41$coefficients[2],2),"(",round(se41,2),")")
T4$X4[2] <- paste(round(fit42$coefficients[2],2),"(",round(se42,2),")")  
T4$X4[3] <- round(elast4,2)  
T4$X4[4] <- round(pct_effect4,2)
T4$X4[5] <- obs4
T4$X4[6] <- round(R_sqrd4,3)

T4$X5[1] <- paste(round(fit51$coefficients[2],2),"(",round(se51,2),")")
T4$X5[2] <- paste(round(fit52$coefficients[2],2),"(",round(se52,2),")")  
T4$X5[3] <- round(elast5,2)  
T4$X5[4] <- round(pct_effect5,2)
T4$X5[5] <- obs5
T4$X5[6] <- round(R_sqrd5,3)

T4$X6[1] <- paste(round(fit61$coefficients[2],2),"(",")",round(se61,2))
T4$X6[2] <- paste(round(fit62$coefficients[2],2),"(",")",round(se62,2))  
T4$X6[3] <- round(elast6,2)  
T4$X6[4] <- round(pct_effect6,2)
T4$X6[5] <- round(obs6,2)
T4$X6[6] <- round(R_sqrd6,2)

# rename cols and rows
rownames(T4) <- c("New Jersey dummy,\n no controls",
                  "New Jersey dummy,\n controls for chain \n and ownership",
                  "Implied elasticity",
                  "Percentage effect",
                  "Number of observations",
                  "Adjusted R2")

colnames(T4) <- c("CK results \n (1)",
                  "Add observations \n missing starting \n wages or data on \n managers \n (2)",
                  "Drop \n observations on \n BK and KFC \n company-owned \n restaurants \n (3)",
                  "Sampled \n universe \n (4)",
                  "Single \n payroll \n period \n (5)",
                  "Averages of \n payroll data \n (6)")
T4 %>% kbl()  # round it!
                  
```

